export const data = {
  childNodes: [
    {
      id: 1,
      title:
        '‘Shang-Chi’ Stays On Record Pace With Nearly $35.8 Million In Second Weekend;',
      author: 'moderator',
      like: 2250,
      dislike: 3250,
      comments: 5414,
      date: '2022-02-24',
      time: '9:41',
      imagePath: 'comment.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit, sed do eiusmod tempor consectetur Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 2,
      title:
        'Daniel Craig: post your questions for the actor ahead of his final Bond film',
      author: 'moderator1',
      like: 1350,
      dislike: 2050,
      comments: 2253,
      date: '2027-02-24',
      time: '4:41',
      imagePath: 'comment1.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.',
    },
    {
      id: 3,
      title:
        'I Carry You With Me review – hybrid feature charts a longterm love',
      author: 'moderator2',
      like: 160,
      dislike: 1250,
      comments: 1002,
      date: '2023-02-24',
      time: '11:41',
      imagePath: 'comment2.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem',
    },
    {
      id: 4,
      title: 'La Cha Cha review – caravan park comedy is fun, for the cast',
      author: 'moderator3',
      like: 50,
      dislike: 250,
      comments: 540,
      date: '2019-07-20',
      time: '19:41',
      imagePath: 'comment3.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit, sed do eiusmod tempor consectetur Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 5,
      title: 'One Of Us Is Lying: Release Date, Cast, And More',
      author: 'moderator4',
      like: 2250,
      dislike: 2250,
      comments: 541,
      date: '2017-11-11',
      time: '9:41',
      imagePath: 'comment4.png',
      profileImage: '4cf433f8d4d5885fad094245b3920133.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adsed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 6,
      title:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor',
      author: 'moderator',
      like: 2250,
      dislike: 2250,
      comments: 541,
      date: '2017-11-11',
      time: '9:41',
      imagePath: 'comment.png',
      profileImage: '6ef8449d61901cad39f2adc0b5a404cf.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiectetur adipiscing elit, sed do eiusmod tempor consectetur lit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 7,
      title:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor',
      author: 'moderator',
      like: 2250,
      dislike: 2250,
      comments: 541,
      date: '2017-11-11',
      time: '9:41',
      imagePath: 'comment.png',
      profileImage: '333db814aa02093c1d7287796c88ff58-2.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adiped do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 8,
      title:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor',
      author: 'moderator',
      like: 2250,
      dislike: 2250,
      comments: 541,
      date: '2017-11-11',
      time: '9:41',
      imagePath: 'comment.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 'Lorem adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit, sed do eiusmod tempor consectetur Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
    {
      id: 9,
      title:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor',
      author: 'moderator',
      like: 2250,
      dislike: 2250,
      comments: 541,
      date: '2017-11-11',
      time: '9:41',
      imagePath: 'comment.png',
      profileImage: '333db814aa02093c1d7287796c88ff58.png',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit, sed do eiusmod tempor consectetur Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetur adipiscing elit,Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor consectetu adipisc sit ameth...',
    },
  ],
};

